UIWEB/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessEntity;
using DataAccess;


namespace UIWEB.Controllers
{
    public class BancoController : Controller
    {
        BancoDA oBancoDA = new BancoDA();
        SucursalDA oSucursalDA = new SucursalDA();

        // GET: Banco
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetBancos()
        {
            List<BancoBE> listaBancos = oBancoDA.Get();
            return Json(listaBancos, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBancoNuevo()
        {
            BancoBE oBancoNuevoBE = new BancoBE();
            return Json(oBancoNuevoBE, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Insert(BancoBE pBancoBE)
        {
            BancoBE oBancoBE = oBancoDA.Insert(pBancoBE);
            return Json(new { success = true, message = "OK", obj = pBancoBE });
        }

        [HttpPost]
        public JsonResult Delete(BancoBE pBancoBE)
        {
            SucursalBE.Criterio oCriterio= new SucursalBE.Criterio();
            oCriterio.BancoId=pBancoBE.Id;
            var ltsResultado= oSucursalDA.Get(oCriterio);

            if (ltsResultado.Count>0)
                return Json(new { success = false, message = "No se puede eliminar la banca porque tiene sucursales asociadas." });

            oBancoDA.Delete(pBancoBE);
            return Json(new { success = true, message = "OK" });


        }
    }
}

UIWEB/Controllers/OrdenPagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessEntity;
using DataAccess;

namespace UIWEB.Controllers
{
    public class OrdenPagoController : Controller
    {
        BancoDA oBancoDA = new BancoDA();
        SucursalDA oSucursalDA = new SucursalDA();
        MonedaDA oMonedaDA = new MonedaDA();
        EstadoDA oEstadoDA = new EstadoDA();
        OrdenPagoDA oOrdenPagoDA = new OrdenPagoDA();
        // GET: OrdenPago
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetOrdenPagos()
        {
            List<OrdenPagoBE> listaOrdenPagoes = oOrdenPagoDA.Get(null);
            return Json(listaOrdenPagoes, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetOrdenPagoNuevo()
        {

            return Json(OrdenPagoNuevo(), JsonRequestBehavior.AllowGet);
        }

        private OrdenPagoBE OrdenPagoNuevo()
        {
            OrdenPagoBE oOrdenPagoBE = new OrdenPagoBE();
            MonedaBE oMonedaBE = new MonedaBE();
            SucursalBE oSucursalBE = new SucursalBE();
            EstadoBE oEstadoBE = new EstadoBE();

            oMonedaBE.Nombre = "Seleccione";
            oMonedaBE.Id = 0;

            oSucursalBE.NombreCombo = "Seleccione";
            oSucursalBE.Id = 0;

            oEstadoBE.Nombre = "Seleccione";
            oEstadoBE.Id = 0;

            oOrdenPagoBE.CfgMonedas = oMonedaDA.Get();
            oOrdenPagoBE.CfgSucursals = oSucursalDA.Get(null);
            oOrdenPagoBE.CfgEstados = oEstadoDA.Get();

            oOrdenPagoBE.CfgSucursals.Insert(0, oSucursalBE);
            oOrdenPagoBE.CfgMonedas.Insert(0, oMonedaBE);
            oOrdenPagoBE.CfgEstados.Insert(0, oEstadoBE);
            return oOrdenPagoBE;
        }


        [HttpPost]
        public JsonResult Delete(OrdenPagoBE pOrdenPagoBE)
        {
            oOrdenPagoDA.Delete(pOrdenPagoBE);
            return Json("OK");

        }

        [HttpPost]
        public JsonResult Insert(OrdenPagoBE pOrdenPagoBE)
        {
            if (pOrdenPagoBE.Sucursal.Id == 0)
            {
                return Json(new { success = false, message = "Seleccionar una sucursal" }, JsonRequestBehavior.AllowGet);
            }

            if (pOrdenPagoBE.Moneda.Id == 0)
            {
                return Json(new { success = false, message = "Seleccionar un tipo de moneda" }, JsonRequestBehavior.AllowGet);
            }

            if (pOrdenPagoBE.Estado.Id == 0)
            {
                return Json(new { success = false, message = "Seleccionar un estado" }, JsonRequestBehavior.AllowGet);
            }

           
            if (pOrdenPagoBE.Estado.Id == 0)
            {
                return Json(new { success = false, message = "Seleccionar un estado" }, JsonRequestBehavior.AllowGet);
            }

            try
            {
                pOrdenPagoBE.FechaPago = Convert.ToDateTime(pOrdenPagoBE.FechaPagoString);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "La fecha de pago no tiene el formato correcto" }, JsonRequestBehavior.AllowGet);

            }

            OrdenPagoBE oOrdenPagoBE = oOrdenPagoDA.Insert(pOrdenPagoBE);
            return Json(new { success = true, message = "OK", obj = oOrdenPagoBE });

        }
    }
}

UIWEB/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessEntity;
using DataAccess;
using System.Net;
using System.ServiceModel.Web;

namespace UIWEB.Controllers
{
    public class SucursalController : Controller
    {
        SucursalDA oSucursalDA = new SucursalDA();
        BancoDA oBancoDA = new BancoDA();
        OrdenPagoDA oOrdenPagoDA = new OrdenPagoDA();
        private SucursalBE SucursalNuevo()
        {
            SucursalBE oSucursalBE = new SucursalBE();
            BancoBE oBancoBE = new BancoBE();
            oBancoBE.Nombre = "Seleccione";
            oBancoBE.Id = 0;

            oSucursalBE.CfgBancos = oBancoDA.Get();
            oSucursalBE.CfgBancos.Insert(0, oBancoBE);
        
            return oSucursalBE;
        }


       
        // GET: Sucursal
        public ActionResult Index()
        {
            return View();
        }
       

        public JsonResult GetSucursals()
        {
            List<SucursalBE> listaSucursales = oSucursalDA.Get(null);
            return Json(listaSucursales, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSucursalNuevo()
        {
           
            return Json(SucursalNuevo(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Insert(SucursalBE pSucursalBE)
        {
            if (pSucursalBE.Banco.Id == 0) {
                return Json(new { success = false, message = "Seleccionar un Banco" },JsonRequestBehavior.AllowGet);
            }

            SucursalBE oSucursalBE = oSucursalDA.Insert(pSucursalBE);
            return Json(new { success = true, message = "OK", obj = oSucursalBE });

        }

        [HttpPost]
        public JsonResult Delete(SucursalBE pSucursalBE)
        {
            OrdenPagoBE.Criterio oCriterio = new OrdenPagoBE.Criterio();
            oCriterio.SucursalId = pSucursalBE.Id;
            var ltsResultado = oOrdenPagoDA.Get(oCriterio);

            if (ltsResultado.Count > 0)
                return Json(new { success = false, message = "No se puede eliminar la sucursal porque tiene ordenes de pagos asociadas." });

            oSucursalDA.Delete(pSucursalBE);
            return Json(new { success = true, message = "OK" });

        }
    }
}

UIWEB/Views/Banco/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/angularJs/Controladores/BancoControlador.js"></script>
<div id="divBanco" ng-controller="BancoControlador as cBanco">

    
    <div class="row">
        <div class="col-md-8">
            <div dismiss-on-timeout="4000" uib-alert ng-class="'alert-' + (cBanco.AlertaTipo || 'warning')" close="cBanco.CloseAlert()" ng-if="cBanco.MostrarValidacion">{{cBanco.AlertaMensaje}}</div>

            <h1>
                Banco
          
                <button type="button" class="btn btn-warning" aria-label="Left Align" ng-click="cBanco.Nuevo()">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
            </h1>
        </div>
        <div class="col-md-4">
        </div>
       
    </div>




    <table class="table table-striped table-bordered table-hover" datatable="ng" dt-options="cBanco.dtOptions">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Direccion</th>
                <th>Fecha Registro</th>
                <th>acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr data-ng-repeat="Banco in cBanco.Bancos">
                <td>{{Banco.Id}}</td>
                <td>{{Banco.Nombre}}</td>
                <td>{{Banco.Direccion}}</td>
                <td>{{Banco.FechaRegistroString}}</td>
                <td>


                    <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="cBanco.Eliminar(Banco,$index)">
                        <span class="glyphicon glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>

        </tbody>

    </table>

</div>

UIWEB/Views/OrdenPago/Index.cshtml
@{
    ViewBag.Title = "Index";
}



<script src="~/Scripts/angularJs/Controladores/OrdenPagoControlador.js"></script>
<div id="divBanco" ng-controller="OrdenPagoControlador as cOrdenPago">

    <div class="row">
        <div class="col-md-8">
            <h1>
                OrdenPago
                <button type="button" class="btn btn-warning" aria-label="Left Align" ng-click="cOrdenPago.Nuevo()">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
            </h1>
        </div>
        <div class="col-md-4">
        </div>
    </div>




    <table class="table table-striped table-bordered table-hover" datatable="ng" dt-options="cOrdenPago.dtOptions">
        <thead>
            <tr>
                <th>Id</th>
                <th>Banco</th>
                <th>Sucursal</th>
                <th>Monto</th>
                <th>Moneda</th>
                <th>Estado</th>
                <th>FechaPagoString</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr data-ng-repeat="OrdenPago in cOrdenPago.OrdenPagos">
                <td>{{OrdenPago.Id}}</td>
                <td>{{OrdenPago.Sucursal.Banco.Nombre}}</td>
                <td>{{OrdenPago.Sucursal.Nombre}}</td>
                <td>{{OrdenPago.Monto}}</td>
                <td>{{OrdenPago.Moneda.Nombre}}</td>
                <td>{{OrdenPago.Estado.Nombre}}</td>
                <td>{{OrdenPago.FechaPagoString}}</td>
                <td>

                    <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="cOrdenPago.Eliminar(OrdenPago,$index)">
                        <span class="glyphicon glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>

        </tbody>

    </table>

</div>

UIWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>


    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Angular -->
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-route.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap.min.js"></script>
    <script src="~/Scripts/angular-mocks.js"></script>
    <script src="~/Scripts/angular-animate.min.js"></script>
    <script src="~/Scripts/angular-touch.min.js"></script>

    <script src="~/Scripts/angularJs/Configuracion.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>


    <script src="~/Scripts/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/datatables/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/datatables/angular-datatables.min.js"></script>
    <script src="~/Scripts/datatables/datatables.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Banco", "Index", "Banco", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Sucursal", "Index", "Sucursal", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Orden de Pago", "Index", "OrdenPago", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        <div ng-app="myApp" class="row">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

   



</body>
</html>

UIWEB/Views/Sucursal/Index.cshtml
@{
    ViewBag.Title = "Index";
}



<script src="~/Scripts/angularJs/Controladores/SucursalControlador.js"></script>
<div id="divBanco" ng-controller="SucursalControlador as cSucursal">

    <div class="row">
        <div class="col-md-8">
            <div dismiss-on-timeout="4000" uib-alert ng-class="'alert-' + (cSucursal.AlertaTipo || 'warning')" close="cSucursal.CloseAlert()" ng-if="cSucursal.MostrarValidacion">{{cSucursal.AlertaMensaje}}</div>

            <h1>
                Sucursal
                <button type="button" class="btn btn-warning" aria-label="Left Align" ng-click="cSucursal.Nuevo()">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
            </h1>
        </div>
        <div class="col-md-4">
        </div>
    </div>




    <table class="table table-striped table-bordered table-hover" datatable="ng" dt-options="cSucursal.dtOptions">
        <thead>
            <tr>
                <th>Id</th>
                <th>Banco</th>
                <th>Nombre</th>
                <th>Direccion</th>
                <th>Fecha Registro</th>
                <th>acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr data-ng-repeat="Sucursal in cSucursal.Sucursals">
                <td>{{Sucursal.Id}}</td>
                <td>{{Sucursal.Banco.Nombre}}</td>
                <td>{{Sucursal.Nombre}}</td>
                <td>{{Sucursal.Direccion}}</td>
                <td>{{Sucursal.FechaRegistroString}}</td>
                <td>

                    <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="cSucursal.Eliminar(Sucursal,$index)">
                        <span class="glyphicon glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>

        </tbody>

    </table>

</div>